bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind h swap-pane -s '{left-of}'
bind j swap-pane -s '{down-of}'
bind k swap-pane -s '{up-of}'
bind l swap-pane -s '{right-of}'
